env:
  browser: true
  es6: true
  node: true
extends: 'typescript'
parserOptions:
  sourceType: module
rules:
  no-console:
    - allow
  indent:
    - error
    - tab
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - never
