service:
  name: aws-nodejs-typescript

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: "${self:custom.aws.region}"
  profile: "${self:custom.app.name}" # used to lookup credentials in ~/.aws/credentials

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello
