service:
  name: trello-powerup

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager

provider:
  name: aws
  runtime: nodejs6.10
  stage: prod
  region: ${file(./config/aws.json):region}
  profile: ${file(./config/app.json):name} # used to lookup credentials in ~/.aws/credentials

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

custom:
  customDomain:
    domainName: trello.shaheenghiassy.com
    basePath: ''
    certificateName: '*.shaheenghiassy.com'
    stage: ${self:provider.stage}
    endpointType: 'regional'
